### ISSUE TITLE
Create a progress bar header that tracks the user progress

### ISSUE THREAD

**Issue by mark-yacoub** [mark-yacoub/metremenqeemi#9]
Across the same level, the user should see a progress bar of their progress, and maybe insights like time spent per lesson or overall untiil the finish line.

**Comment by mark-yacoub** [comment]
@ysawires  wanna do this?
now that you're familiar with navigation, wanna create a bar on top that persists across all screen that tracks the progress?

**Comment by ysawires** [comment]
@mark-yacoub Sure I can assign it to myself. But should we do some of the lesson content and screens first?

**Comment by mark-yacoub** [comment]
yeah I'm working on the first one. just thought it would tie well with what you just did. and you'll only do it with dummy data.
